# Generated by Django 5.1.3 on 2024-12-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plp_listings', '0002_listing_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(default='listing_images/default.jpg', upload_to='listing_images/'),
        ),
    ]
