# Generated by Django 5.1.3 on 2024-12-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plp_listings', '0003_alter_listingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listing_images/'),
        ),
    ]
